language: java
jdk:
  - openjdk8
script:
  - mvn jaxb2:xjc compile install
notifications:
  slack:
    - secure: Tu8/YbtUCSBWiZ0J+2Ai99SuOOL9uNysgDDEVyHHRAXUUwyX5eB0FY3SqxttHp32KHOa/2RDhg/eJoKiVNt2wOI1PAAFCzGedwlGQk2tY17ASdtnyxJTv8R6yeFQ+o4fVjcmhGnTF1u8Z/22MrjrY4DRlXX9f+MNGSU0OR7/NTg7P/ZaiB7XT35/qxJwLkU5ThGlwc4O4aqzeWfD4gb+ErME1MwW1nsFOHQUeXua5cXH/OnaFRomPzox+6cIz856lT63lNmdZFwihdKtutTpd/2O98hdSRmoN5Mw9XYGXpPa9kYvva+cBLur8GhtaMBFtjL84TJL44wwJFnAgs5jcTPmBxgncG7ED8Zhx+FZn3PQOytDW6TkJJa0aWdJ5Ezw49F32lBf//xBqo3+Rv29RJ+Iwhx52K4ZkPT2xgFGu2g2bdyZa6QIDdiujb9Ats5myhWtV+7xlH94FOFxIVj3Hs3tw0sWx4xa0QyC27REkUmU/lP93F469QYXdVZlRJqeJHXDWTTyjB0j+jt7ouzpnz81Okvzs2BKIoprXTxxCt2u9kdVy4ctJcs4ZivE5VhlLO1WZLAgF9UDWvjHHKwLtwG8t5xEqBxmR9OBGzl1fWY0RIURou3GE4OBAscPyvatFozqa81yHZL3selHLhe82v9FLdPBArr8q5E/WGNrxF0=
